name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and Angular CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Create Zip File
        run: |
          cd dist/angular-15-crud-app-anvi
          zip -r angular-15-crud-app.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angular-15-crud-app-anvi
          path: dist/angular-15-crud-app-anvi/angular-15-crud-app.zip
